DROP TABLE IF EXISTS public.full_dataset;

-- generated from DBeaver
CREATE TABLE public.full_dataset (
	qty_dot_url int4 NULL,
	qty_hyphen_url int4 NULL,
	qty_underline_url int4 NULL,
	qty_slash_url int4 NULL,
	qty_questionmark_url int4 NULL,
	qty_equal_url int4 NULL,
	qty_at_url int4 NULL,
	qty_and_url int4 NULL,
	qty_exclamation_url int4 NULL,
	qty_space_url int4 NULL,
	qty_tilde_url int4 NULL,
	qty_comma_url int4 NULL,
	qty_plus_url int4 NULL,
	qty_asterisk_url int4 NULL,
	qty_hashtag_url int4 NULL,
	qty_dollar_url int4 NULL,
	qty_percent_url int4 NULL,
	qty_tld_url int4 NULL,
	length_url int4 NULL,
	qty_dot_domain int4 NULL,
	qty_hyphen_domain int4 NULL,
	qty_underline_domain int4 NULL,
	qty_slash_domain int4 NULL,
	qty_questionmark_domain int4 NULL,
	qty_equal_domain int4 NULL,
	qty_at_domain int4 NULL,
	qty_and_domain int4 NULL,
	qty_exclamation_domain int4 NULL,
	qty_space_domain int4 NULL,
	qty_tilde_domain int4 NULL,
	qty_comma_domain int4 NULL,
	qty_plus_domain int4 NULL,
	qty_asterisk_domain int4 NULL,
	qty_hashtag_domain int4 NULL,
	qty_dollar_domain int4 NULL,
	qty_percent_domain int4 NULL,
	qty_vowels_domain int4 NULL,
	domain_length int4 NULL,
	domain_in_ip int4 NULL,
	server_client_domain int4 NULL,
	qty_dot_directory int4 NULL,
	qty_hyphen_directory int4 NULL,
	qty_underline_directory int4 NULL,
	qty_slash_directory int4 NULL,
	qty_questionmark_directory int4 NULL,
	qty_equal_directory int4 NULL,
	qty_at_directory int4 NULL,
	qty_and_directory int4 NULL,
	qty_exclamation_directory int4 NULL,
	qty_space_directory int4 NULL,
	qty_tilde_directory int4 NULL,
	qty_comma_directory int4 NULL,
	qty_plus_directory int4 NULL,
	qty_asterisk_directory int4 NULL,
	qty_hashtag_directory int4 NULL,
	qty_dollar_directory int4 NULL,
	qty_percent_directory int4 NULL,
	directory_length int4 NULL,
	qty_dot_file int4 NULL,
	qty_hyphen_file int4 NULL,
	qty_underline_file int4 NULL,
	qty_slash_file int4 NULL,
	qty_questionmark_file int4 NULL,
	qty_equal_file int4 NULL,
	qty_at_file int4 NULL,
	qty_and_file int4 NULL,
	qty_exclamation_file int4 NULL,
	qty_space_file int4 NULL,
	qty_tilde_file int4 NULL,
	qty_comma_file int4 NULL,
	qty_plus_file int4 NULL,
	qty_asterisk_file int4 NULL,
	qty_hashtag_file int4 NULL,
	qty_dollar_file int4 NULL,
	qty_percent_file int4 NULL,
	file_length int4 NULL,
	qty_dot_params int4 NULL,
	qty_hyphen_params int4 NULL,
	qty_underline_params int4 NULL,
	qty_slash_params int4 NULL,
	qty_questionmark_params int4 NULL,
	qty_equal_params int4 NULL,
	qty_at_params int4 NULL,
	qty_and_params int4 NULL,
	qty_exclamation_params int4 NULL,
	qty_space_params int4 NULL,
	qty_tilde_params int4 NULL,
	qty_comma_params int4 NULL,
	qty_plus_params int4 NULL,
	qty_asterisk_params int4 NULL,
	qty_hashtag_params int4 NULL,
	qty_dollar_params int4 NULL,
	qty_percent_params int4 NULL,
	params_length int4 NULL,
	tld_present_params int4 NULL,
	qty_params int4 NULL,
	email_in_url int4 NULL,
	time_response float4 NULL,
	domain_spf int4 NULL,
	asn_ip int4 NULL,
	time_domain_activation int4 NULL,
	time_domain_expiration int4 NULL,
	qty_ip_resolved int4 NULL,
	qty_nameservers int4 NULL,
	qty_mx_servers int4 NULL,
	ttl_hostname int4 NULL,
	tls_ssl_certificate int4 NULL,
	qty_redirects int4 NULL,
	url_google_index int4 NULL,
	domain_google_index int4 NULL,
	url_shortened int4 NULL,
	phishing int4 NULL
);

COPY full_dataset
FROM '/opt/data/dataset_full.csv'
DELIMITER ','
CSV HEADER;

create table new_data as select * from full_dataset limit 0;
alter table new_data add full_url text;
alter table new_data add phish_probability float;
alter table new_data add id int generated always as identity;

COMMIT;