version: "3.9"

services:
  jupyter:
    build: ./docker/jupyter
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - JUPYTER_TOKEN=${pg_pw}
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work/notebooks
      - ./jupyter/models:/home/jovyan/work/models
      - ./jupyter/pages:/home/jovyan/work/pages

  pg:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=daan
      - POSTGRES_PASSWORD=${pg_pw}
      - POSTGRES_DB=phishing_data
    ports:
      - "5432:5432"
    volumes:
      - ./data:/opt/data
      - ./docker/postgres:/docker-entrypoint-initdb.d